### ISSUE TITLE
are these typos

### ISSUE THREAD

**Issue by HansHammel** [jclevy/chocolatejs#7]
insert_nade
update_nade
link_nade
merge_nade
remove_nade

nade!?

**Comment by jclevy** [comment]
Yes, these are typos. Hope I'll come back soon on that.

**Comment by HansHammel** [comment]
You are very consistent with your typing errors :stuck_out_tongue_winking_eye:

**Comment by jclevy** [comment]
At least, something I'm still good at! :sweat_smile: 
BTW are you using ChocolateJS?

**Comment by HansHammel** [comment]
Nope, I am working on a similar project and chocolatejs has plenty of the stuff I would want for the first release of my "real full stack" framework. I was just spying on your code. Maybe we can collaborate. You are not coincidental at the CeBit in Hanover or at JSUnconf in Hamburg? BTW: I hate coffee script, it's just one more meta-language with rare support in terms of tooling, ides, etc. Does coffeescript make use of cutting edge ECMAScript features!? My whole approach is quite similar, like there are mandatory things developers need to be more productive e.g. an ide/api to save things back to disk (without chromes workspace) esp. for inplace style-editing, markdown support (as a filebased cms, as well as for documentation purpose), jasmine tests on a per view/page/component base (my clou is, each component gets its jasmine tests attatched to the end of the page, that works well on desktops and mobiles, you can edit your current components view and run the tests each time something changes, on mobiles you will get a audio feedback so you don't have to scoll down to see the failing tests), a selfhosted multi-tenant PKI suitable even for mobile. proxy and loadbalancing stuff. But I try to go further including thinds like configuration management, fault tolerance, provisioning and auto-scaling, codestyle-checking, security-tools, an automated/intelligent component-transformation/transpilation-capability (hard to explain in short words), service discovery, centralized loggin (muteable by file), autotranslation, usermanagement, etc.  and many more. Its a raw concept at the moment. I am reworking it for a reduced, stable release. I am leveraging a lot of existing projects, and so I am interested in yours. Regards, Oliver.

**Comment by jclevy** [comment]
Waou! So many services to integrate. I have the same kind of goal in ChocolateJS but not as absolutely complete. Unfortunately I won't be at CeBit nor at JSUnconf but I would glad to follow your project. I know many developers hate Coffescript but I do like this language. I chose Coffeescript at a time I was developing a lot of code in python and javascript and I wanted to have only one language to use client-side and server-side. Coffeescript inspired some of the new es6 features and I like the fact that it forces me to do some kind of pair programing alone by comparing the intent I put in the coffeescript code with the transpiled javascript it produces (I do that in the Lab panel of my online ide). Good luck with your project and keep me informed.
